import React, { useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { Info } from 'lucide-react';

const DICTIONARY: Record<string, string> = {
  'bottleneck': "A sharp reduction in the size of a population due to environmental events (like earthquakes, floods, fires, or disease) or human activities. This reduces the variation in the gene pool.",
  'genetic drift': "The change in frequency of an existing gene variant in the population due to random chance. It's like flipping a coin 100 times; you won't always get exactly 50 heads.",
  'missense': "A genetic alteration in which a single base pair substitution results in the translation of a different amino acid at that position.",
  'nonsense': "A genetic alteration that causes the premature termination of a protein. The protein is usually incomplete and non-functional.",
  'variant call': "The conclusion that a specific genomic position in a sample differs from the reference genome.",
  'read': "A short fragment of DNA sequence generated by a sequencer.",
  'reference genome': "A digital nucleic acid sequence database, assembled by scientists as a representative example of the set of genes in one idealized individual organism.",
  'rsid': "Reference SNP cluster ID. A unique identifier used by researchers and databases to refer to specific SNPs.",
  'frameshift': "A genetic mutation caused by indels (insertions or deletions) of a number of nucleotides in a DNA sequence that is not divisible by three.",
  'recombination': "The rearrangement of genetic material, especially by crossing over in chromosomes or by the artificial joining of segments of DNA from different organisms.",
  'hydrophobic': "Tending to repel or fail to mix with water.",
  'hydrophilic': "Having a tendency to mix with, dissolve in, or be wetted by water."
};

export const GlossaryTerm: React.FC<{ term: string; children: React.ReactNode }> = ({ term, children }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [coords, setCoords] = useState({ top: 0, left: 0 });
  const spanRef = useRef<HTMLSpanElement>(null);

  // Normalize term for dictionary lookup
  const cleanTerm = term.toLowerCase().replace(/[^a-z ]/g, "");
  // Try exact match, then fuzzy logic if needed (or just ensure dictionary has keys)
  const def = DICTIONARY[cleanTerm] || DICTIONARY[Object.keys(DICTIONARY).find(k => k.includes(cleanTerm)) || ''] || "Definition not found.";

  useEffect(() => {
    if (isOpen && spanRef.current) {
      const rect = spanRef.current.getBoundingClientRect();
      setCoords({
        top: rect.top - 10, // Just above the element
        left: rect.left + rect.width / 2
      });
    }
  }, [isOpen]);

  return (
    <>
      <span 
        ref={spanRef}
        className="cursor-help border-b-2 border-blue-300 hover:bg-blue-100 transition-colors inline-block"
        onMouseEnter={() => setIsOpen(true)}
        onMouseLeave={() => setIsOpen(false)}
        onClick={() => setIsOpen(!isOpen)}
      >
        {children}
      </span>
      {isOpen && createPortal(
        <div 
            className="fixed z-[9999] w-64 p-3 bg-slate-900 text-white text-xs rounded-lg shadow-xl pointer-events-none transition-opacity duration-200"
            style={{ 
                top: coords.top, 
                left: coords.left, 
                transform: 'translate(-50%, -100%)' 
            }}
        >
          <div className="font-bold mb-1 border-b border-slate-700 pb-1 flex items-center gap-1">
             <Info size={12} className="text-blue-400"/> {term}
          </div>
          {def}
          <div className="absolute top-full left-1/2 -translate-x-1/2 border-8 border-transparent border-t-slate-900"></div>
        </div>,
        document.body
      )}
    </>
  );
};